# Site settings
title: Why Software Development?
header-img: img/home-bg.png
email: shannonkmc@hotmail.com
copyright_name: magpiemac
description: > # this means to ignore newlines until "baseurl:"
  Adventures in Programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  magpiemac
learn_profile: magpiemac
email_username: shannonkmc@hotmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
